#!/usr/bin/env python3
"""
gen_plans_index.py — Scan plans/**/*.md, categorise by prefix, sort by
modification time (newest first within each section), and emit plans/INDEX.md.

Usage:
    python3 scripts/gen_plans_index.py            # write plans/INDEX.md
    python3 scripts/gen_plans_index.py --check    # exit 1 if INDEX.md is stale
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLANS_DIR = REPO_ROOT / "plans"
INDEX_PATH = PLANS_DIR / "INDEX.md"

# Files to exclude from the index entirely.
_EXCLUDE = {"INDEX.md"}

# Map sub-directory name (or root level) → section header.
# Ordered: root files first, then sub-directories alphabetically.
_SECTION_ORDER = [
    (".", "plans/ (root)"),
    ("adrs", "adrs/"),
    ("archive", "archive/"),
    ("dbt", "dbt/"),
    ("docs", "docs/"),
    ("ecosystem", "ecosystem/"),
    ("infra", "infra/"),
    ("lineage", "lineage/"),
    ("patterns", "patterns/"),
    ("performance", "performance/"),
    ("safety", "safety/"),
    ("sql", "sql/"),
    ("testing", "testing/"),
]

# Type classification based on filename stem prefix.
_TYPE_MAP = [
    ("ADR-", "ADR"),
    ("GAP_", "GAP"),
    ("REPORT_", "REPORT"),
    ("STATUS_", "STATUS"),
    ("MIGRATION_", "MIGRATION"),
    ("TESTING_GAPS", "GAP"),
    ("TEST_SUITE_", "PLAN"),
]
_DEFAULT_TYPE = "PLAN"


def _classify(stem: str) -> str:
    for prefix, kind in _TYPE_MAP:
        if stem.upper().startswith(prefix):
            return kind
    return _DEFAULT_TYPE


def _first_heading(path: Path) -> str:
    """Return the text of the first non-empty heading in the file, or stem."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return path.stem
    for line in text.splitlines():
        m = re.match(r"^#{1,3}\s+(.+)", line)
        if m:
            # Strip trailing badge/emoji noise
            title = m.group(1).strip()
            # Remove markdown links
            title = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", title)
            # Remove bold/italic markers
            title = re.sub(r"\*+([^*]+)\*+", r"\1", title)
            # Truncate
            if len(title) > 90:
                title = title[:87] + "…"
            return title
    return path.stem


def _rel_link(path: Path) -> str:
    """Return a relative markdown link from plans/ to path."""
    try:
        rel = path.relative_to(PLANS_DIR)
    except ValueError:
        return str(path)
    return str(rel).replace("\\", "/")


def collect_files() -> dict[str, list[Path]]:
    """Return dict mapping section key → list of .md files, sorted by mtime desc."""
    sections: dict[str, list[tuple[float, Path]]] = {k: [] for k, _ in _SECTION_ORDER}

    for md in PLANS_DIR.rglob("*.md"):
        if md.name in _EXCLUDE:
            continue
        rel = md.relative_to(PLANS_DIR)
        parts = rel.parts
        if len(parts) == 1:
            key = "."
        elif len(parts) >= 2:
            key = parts[0]
        else:
            key = "."

        if key not in sections:
            sections[key] = []

        try:
            mtime = md.stat().st_mtime
        except OSError:
            mtime = 0.0
        sections[key].append((mtime, md))

    result: dict[str, list[Path]] = {}
    for key, _ in _SECTION_ORDER:
        files = sections.get(key, [])
        # Sort by mtime descending (newest first), then name for stability.
        files.sort(key=lambda x: (-x[0], x[1].name))
        result[key] = [f for _, f in files]

    return result


def generate(sections: dict[str, list[Path]]) -> str:
    """Generate the full INDEX.md content."""
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        "# plans/ — Document Index",
        "",
        f"> Auto-generated by `scripts/gen_plans_index.py` on {now}.",
        "> Sorted newest-first within each section (by file modification time).",
        "> Run `python3 scripts/gen_plans_index.py` to regenerate.",
        "",
        "**Type key:** "
        "PLAN = implementation plan · "
        "GAP = gap/comparison analysis · "
        "REPORT = research/assessment · "
        "ADR = architecture decision · "
        "STATUS = progress tracking · "
        "MIGRATION = migration procedure",
        "",
        "---",
        "",
    ]

    for key, header in _SECTION_ORDER:
        files = sections.get(key, [])
        if not files:
            continue

        lines.append(f"## {header}")
        lines.append("")
        lines.append("| File | Type | Summary |")
        lines.append("|------|------|---------|")

        for path in files:
            rel = _rel_link(path)
            stem = path.stem
            kind = _classify(stem)
            title = _first_heading(path)
            # Escape pipe characters in title
            title_escaped = title.replace("|", "\\|")
            lines.append(f"| [{path.name}]({rel}) | {kind} | {title_escaped} |")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if plans/INDEX.md is out of date",
    )
    args = parser.parse_args()

    sections = collect_files()
    output = generate(sections)

    if args.check:
        if not INDEX_PATH.exists():
            print(
                f"ERROR: {INDEX_PATH} does not exist.\n"
                "Run: python3 scripts/gen_plans_index.py",
                file=sys.stderr,
            )
            sys.exit(1)
        existing = INDEX_PATH.read_text(encoding="utf-8")
        # Strip the datestamp line for comparison to avoid false positives
        # from timestamp drift (compare everything except line 3).
        def _strip_ts(text: str) -> str:
            lines = text.splitlines()
            stripped = [
                line for line in lines
                if not line.startswith("> Auto-generated by")
            ]
            return "\n".join(stripped)

        if _strip_ts(existing) != _strip_ts(output):
            print(
                "ERROR: plans/INDEX.md is out of date.\n"
                "Run: python3 scripts/gen_plans_index.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print("OK: plans/INDEX.md is up to date.")
    else:
        INDEX_PATH.write_text(output, encoding="utf-8")
        count = sum(len(v) for v in sections.values())
        print(f"OK: plans/INDEX.md updated ({count} files indexed).")


if __name__ == "__main__":
    main()
